MWPW-166756 [mas/io] dynamic settings (#613)
* MWPW-166756 [mas/io] dynamic settings

- using surface wide settings index that can have tags & locale overrides,
- adding in memory cache,
- keep for now 'hard coded' price literals, and collection settings,
- change odinURL api to accept parameters without locale,
- add unit tests

---------

Co-authored-by: cod23684 <cod23684@adobe.com>
Co-authored-by: Mariia Lukianets <lukianet@adobe.com>

diff --git a/.github/workflows/io-tests.yaml b/.github/workflows/io-tests.yaml
--- a/.github/workflows/io-tests.yaml
+++ b/.github/workflows/io-tests.yaml
@@ -8,43 +8,15 @@ on:
 jobs:
     test:
         runs-on: ubuntu-latest
-        defaults:
-            run:
-                working-directory: io/www
-
         steps:
-            - name: Checkout repository
-              uses: actions/checkout@v4
-
-            - name: Setup Node.js
-              uses: actions/setup-node@v4
-              with:
-                  node-version: '22.x'
-                  cache: 'npm'
-                  cache-dependency-path: io/www/package.json
-
-            - name: Install dependencies
-              run: npm ci
-
-            - name: Run Playwright Tests
+            - name: Health Check test
               env:
-                  TEST_URL: https://main--mas--adobecom.aem.live/web-components/docs/ccd.html?mas-io-url=https://${{ secrets.workspace }}.adobeioruntime.net/api/v1/web/MerchAtScale
                   HEALTH_CHECK_URL: https://${{ secrets.workspace }}.adobeioruntime.net/api/v1/web/MerchAtScale/health-check
-              working-directory: nala/io
               run: |
-                  # Install Playwright and its test package
-                  npm install -D @playwright/test playwright
-                  sudo apt-get install xvfb
-                  npx playwright install --with-deps
-
-                  # Run health check test
-                  echo "Running health check test"
-                  npx playwright test ioAutomation.js --grep "@health" --config=playwright.config.js
-
-                  # Run default locale tests
-                  echo "Running default locale tests"
-                  xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npx playwright test ioAutomation.js --grep "@e2e" --config=playwright.config.js
-
-                  # Run French locale tests
-                  echo "Running French locale tests"
-                  TEST_URL="${TEST_URL}&locale=fr_FR" xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npx playwright test ioAutomation.js --grep "@e2e" --config=playwright.config.js
+                  echo "Running health check test on $HEALTH_CHECK_URL"
+                  curl -sf -o /dev/null -w "%{http_code}\n" "$HEALTH_CHECK_URL"
+                  if [ $? -ne 0 ]; then
+                      echo "Health check test failed"
+                      exit 1
+                  fi
+                  echo "Health check test passed"
